global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Moq;
global using ProtoBuf;
global using BlueHeighliner.Comlink;
global using BlueHeighliner.Comlink.Tests;
global using BlueHeighliner.Msmt;
global using BlueHeighliner.MicroGate;
global using Xunit;
global using System.Buffers;
global using System.Buffers.Binary;
global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using System.IO.Compression;
global using System.Net;
global using System.Net.Sockets;
global using System.Security.Cryptography;
global using System.Security.Cryptography.X509Certificates;
global using System.Text;
global using System.Text.Json;
global using System.Windows.Input;
global using CommunityToolkit.Mvvm.Input;
global using ObjectId = LiteDB.ObjectId;
global using System.Runtime.CompilerServices;
global using TestEngineBuilder = BlueHeighliner.Comlink.IEngineBuilder<BlueHeighliner.Comlink.Tests.TestFrame, BlueHeighliner.Comlink.Tests.TestPacket, BlueHeighliner.Comlink.Tests.TestMessagePriority, BlueHeighliner.Comlink.Tests.TestLevel>;
global using TestFrameBuilder = BlueHeighliner.Comlink.IFrameBuilder<BlueHeighliner.Comlink.Tests.TestFrame, BlueHeighliner.Comlink.Tests.TestPacket, BlueHeighliner.Comlink.Tests.TestMessagePriority, BlueHeighliner.Comlink.Tests.TestLevel>;
global using TestPacketBuilder = BlueHeighliner.Comlink.IPacketBuilder<BlueHeighliner.Comlink.Tests.TestFrame, BlueHeighliner.Comlink.Tests.TestPacket, BlueHeighliner.Comlink.Tests.TestMessagePriority, BlueHeighliner.Comlink.Tests.TestLevel>;
